<?xml version="1.0" encoding="utf-8"?>

<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>latest</LangVersion>
    <RootNamespace>S7PlcWebserverApi</RootNamespace>
    <AssemblyName>PLC-Framework.S7PlcWebserverApi</AssemblyName>
  </PropertyGroup>
  
  <!-- External packages -->
  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <Reference Include="System.Net.Http" />
  </ItemGroup>
  
</Project>