<?xml version="1.0" encoding="utf-8"?>

<Project Sdk="Microsoft.NET.Sdk">

  <!-- Main properties -->
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>latest</LangVersion>
    <PlatformTarget>x64</PlatformTarget>
    <RootNamespace>addin</RootNamespace>
    <AssemblyName>PLC-Framework.v20</AssemblyName>
  </PropertyGroup>

  <!-- Siemens properties -->
  <PropertyGroup>
    <SiemensPublicApi Condition="'$(SiemensPublicApi)' == ''">$(MSBuildThisFileDirectory)..\..\..\.lib\Siemens\PublicAPI</SiemensPublicApi>
    <TiaAddInApi>$(SiemensPublicApi)\V20.addIn</TiaAddInApi>
  </PropertyGroup>

  <!-- External references -->
  <ItemGroup>
    <Reference Include="Siemens.Engineering.AddIn">
      <HintPath>$(TiaAddInApi)\Siemens.Engineering.AddIn.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Siemens.Engineering.AddIn.Permissions">
      <HintPath>$(TiaAddInApi)\Siemens.Engineering.AddIn.Permissions.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Siemens.Engineering.AddIn.Utilities">
      <HintPath>$(TiaAddInApi)\Siemens.Engineering.AddIn.Utilities.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Siemens.Engineering.Hmi">
      <HintPath>$(TiaAddInApi)\Siemens.Engineering.Hmi.dll</HintPath>
      <Private>False</Private>
    </Reference>
  </ItemGroup>

</Project>