<?xml version="1.0" encoding="utf-8"?>

<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>latest</LangVersion>
    <RootNamespace>core</RootNamespace>
    <AssemblyName>PLC-Framework.core</AssemblyName>
  </PropertyGroup>

  <!-- References -->
  <ItemGroup>
    <Reference Include="System.Runtime.Serialization" />
  </ItemGroup>

</Project>
